# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CozmoAnim

import flatbuffers

class AnimClip(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAnimClip(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AnimClip()
        x.Init(buf, n + offset)
        return x

    # AnimClip
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AnimClip
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AnimClip
    def Keyframes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .Keyframes import Keyframes
            obj = Keyframes()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def AnimClipStart(builder): builder.StartObject(2)
def AnimClipAddName(builder, Name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(Name), 0)
def AnimClipAddKeyframes(builder, keyframes): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(keyframes), 0)
def AnimClipEnd(builder): return builder.EndObject()
