# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CozmoAnim

import flatbuffers

class AnimClips(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAnimClips(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AnimClips()
        x.Init(buf, n + offset)
        return x

    # AnimClips
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AnimClips
    def Clips(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .AnimClip import AnimClip
            obj = AnimClip()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AnimClips
    def ClipsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def AnimClipsStart(builder): builder.StartObject(1)
def AnimClipsAddClips(builder, clips): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clips), 0)
def AnimClipsStartClipsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def AnimClipsEnd(builder): return builder.EndObject()
